config/routes.rb
Colab::Application.routes.draw do
  resources :discussions do
    resources :posts
  end

  resources :groups do
    resources :permissions
    resources :events
  end

  devise_for :users, :controllers => {:registrations => "registrations"}
  scope "/admin" do
    resources :users
  end

  root :to => 'groups#index'

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  attr_accessible :description, :name, :group_id
  
    belongs_to :group
    has_many :users, :through => :group
    has_many :posts
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @discussions = current_user.discussions.includes(:group, :posts).reverse

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @discussions }
    end
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
    @discussion = Discussion.find(params[:id])
    @group = Group.find(@discussion.group_id)
    @posts = @discussion.posts.includes(:user)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @discussion }
    end
  end

  # GET /discussions/new
  # GET /discussions/new.json
  def new
    @discussion = Discussion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @discussion }
    end
  end

  # GET /discussions/1/edit
  def edit
    @discussion = Discussion.find(params[:id])
  end

  # POST /discussions
  # POST /discussions.json
  def create
    @discussion = Discussion.new(params[:discussion])

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: 'Discussion was successfully created.' }
        format.json { render json: @discussion, status: :created, location: @discussion }
      else
        format.html { render action: "new" }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /discussions/1
  # PUT /discussions/1.json
  def update
    @discussion = Discussion.find(params[:id])

    respond_to do |format|
      if @discussion.update_attributes(params[:discussion])
        format.html { redirect_to @discussion, notice: 'Discussion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    @discussion = Discussion.find(params[:id])
    @discussion.destroy

    respond_to do |format|
      format.html { redirect_to discussions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_form.html.erb
<%= form_for(@discussion) do |f| %>
  <% if @discussion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@discussion.errors.count, "error") %> prohibited this discussion from being saved:</h2>

      <ul>
      <% @discussion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :group %><br />
    <%= f.text_field :group %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/discussions/edit.html.erb
<h1>Editing discussion</h1>

<%= render 'form' %>

<%= link_to 'Show', @discussion %> |
<%= link_to 'Back', discussions_path %>

app/views/discussions/index.html.erb
<div class="page-header">
  <h1>Discussions</h1>
</div>

<% @discussions.each do |discussion| %>
  <div class="row">
    <div class="span4">
      <h3><%= link_to discussion.name, discussion %></h3>
      <p><em><%= discussion.group.name %></em></p>
      <p><%= discussion.description %></p>
    </div>
    <div class="span6">
      <% unless discussion.posts.empty? %>
        <h4>Most Recent Post</h4>
        <% newest_post = discussion.posts.last %>
        <p><%= newest_post.content %></p>
      <% end %>
    </div>
    <div class="span2">
      <h4>Post Count</h4>
      <p><%= discussion.posts.length %></p>
    </div>
  </div>
<% end %>

<br />

<%= link_to 'New Discussion', new_discussion_path %>

app/views/discussions/new.html.erb
<h1>New discussion</h1>

<%= render 'form' %>

<%= link_to 'Back', discussions_path %>

app/views/discussions/show.html.erb
<div class="page-header">
  <h1><small><%= @group.name %>:</small> <%= @discussion.name %></h1>
</div>

<p class="well"><em><%= @discussion.description %></em></p>

<% for post in @posts %>
  <div class="post">
    <div class="row">
      <div class="span3">
        <h4><%= post.user.email %></h4>
        <p><%= post.created_at %></p>
      </div>
      <div class="span9">
        <p><%= post.content %></p>
      </div>
    </div>
    <hr>
  </div>
<% end %>

<%= form_for([@discussion, @discussion.posts.build]) do |f| %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="field">
    <%= f.text_area :content, :cols => 40, :rows => 3 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Edit', edit_discussion_path(@discussion) %> |
<%= link_to 'Back', discussions_path %>