config/routes.rb
Colab::Application.routes.draw do
  resources :discussions do
    resources :posts
  end

  resources :groups do
    resources :permissions
    resources :events
  end

  devise_for :users, :controllers => {:registrations => "registrations"}
  scope "/admin" do
    resources :users
  end

  root :to => 'groups#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name, :is_default
  
  has_many :permissions
  has_many :users, :through => :permissions
  
  has_many :discussions
  has_many :events
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :require_admin_priv, :only => [:new, :edit, :create, :update, :destroy]

  def index
    @permissions = current_user.permissions
    @groups = current_user.groups.includes(:discussions, :events)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])
    @permissions = @group.permissions
    @users = @group.users
    @events = @group.events

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        @admin_permission = Permission.new(:group_id => @group.id, :user_id => current_user.id, :level => 5)
        @admin_permission.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
  
  private
  
  def require_admin_priv
    unless current_user.has_permission(1, 5)
      flash[:error] = "You must be an administrator to do this."
      redirect_to groups_url, :notice => "You must be an administrator to do this."
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.radio_button :is_default, true %>
    <%= f.label :is_default, "True" %>
    <%= f.radio_button :is_default, false %>
    <%= f.label :id_default, "False" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>
<%= link_to 'Destroy', @group, method: :delete, data: { confirm: 'Are you sure?' } %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<div class="page-header">
  <h1>
    Your Groups
    <% if current_user.has_permission(1, 5) %>
      <%= link_to 'New Group', new_group_path, :class => "btn btn-success pull-right" %>
    <% end %>
  </h1>
</div>

<% @groups.each do |group| %>
  <div class="row">
    <div class="span3">
      <h2><%= link_to group.name, group %></h2>
    </div>
    <div class="span4">
      <h3>New Discussions</h3>
      <ul>
      <% for discussion in group.discussions.last(3) %>
        <li><%= link_to discussion.name, discussion %></li>
      <% end %>
      </ul>
    </div>
    <div class="span4">
      <h3>Next Event</h3>
      <% unless group.events.empty? %>
        <% newest_event = group.events.last %>
        <h4><%= newest_event.name %></h4>
        <p><%= newest_event.description %></p>
        <p>Where: <%= newest_event.where %></p>
        <p>When: <%= newest_event.when %></p>
      <% end %>
    </div>
  </div>
  <hr>
<% end %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1>
  <%= @group.name %>
  <div class="btn-group pull-right">
    <%= link_to 'View Permissions', group_permissions_path(@group), :class => "btn" %>
    <%= link_to 'Edit Group', edit_group_path(@group), :class => "btn" %>
  </div>
  </h1>
</div>

<div class="row">

  <div class="span6">
    <h3>Discussions</h3>
    <table class="table">
      <tr>
        <th>Topic</th>
        <th>Posts</th>
      </tr>
      <% for discussion in @group.discussions %>
      <tr>
        <td><%= link_to discussion.name, discussion %></td>
        <td><%= discussion.posts.count %></td>
      </tr>
      <% end %>
    </table>
    
    <h4>Create New Discussion</h4>
    <%= form_for(@group.discussions.build) do |f| %>
      <%= f.hidden_field :group_id, :value => @group.id %>
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :description %>
        <%= f.text_field :description %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
  
  <div class="span6">
    <h3>Upcoming Events</h3>
    <ul>
    <% for event in @events %>
      <li><%= event.name %></li>
    <% end %>
    </ul>
    
    <% if current_user.has_permission(@group.id, 5) %>
      <%= form_for([@group, @group.events.build]) do |f| %>
        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>
        <div class="field">
          <%= f.label :description %>
          <%= f.text_area :description, :cols => 40, :rows => 4 %>
        </div>
        <div class="field">
          <%= f.label :where %>
          <%= f.text_field :where %>
        </div>
        <div class="field">
          <%= f.label :when %>
          <%= f.datetime_select :when %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<div class="row">
  <h3>Users</h3>
  <div class="span8">
    <table>
      <% for user in @users %>
        <tr>
          <td><%= user.email %></td>
          <td>
            <% if current_user.has_permission(@group.id, 4) %>
              <%= link_to 'Destroy', [@group, Permission.where(:user_id => user.id, :group_id => @group.id).first], method: :delete, data: {confirm: 'Are you sure?'} %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="span4">
    <% if current_user.has_permission(@group.id, 4) %>
      <%= form_tag(new_group_permission_path(@group.id), :method => 'get') do %>
        <%= label_tag(:user_email, "User Email:") %>
        <%= text_field_tag(:user_email) %>
        <%= submit_tag("Add Permissions") %>
      <% end %>
    <% end %>
  </div>
</div>