config/routes.rb
Colab::Application.routes.draw do
  resources :discussions do
    resources :posts
  end

  resources :groups do
    resources :permissions
    resources :events
  end

  devise_for :users, :controllers => {:registrations => "registrations"}
  scope "/admin" do
    resources :users
  end

  root :to => 'groups#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  has_many :permissions
  has_many :groups, :through => :permissions
  has_many :discussions, :through => :groups
  has_many :events, :through => :groups
  has_many :posts
  
  def has_permission(group_id, level)
    permissions = self.permissions.where(:group_id => group_id)
    if permissions.any? && permissions.first.level >= level
      return true
    else
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :require_admin_priv, :except => [:edit, :update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @permissions = @user.permissions.includes(:group)
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(params[:user])
    generated_password = Devise.friendly_token.first(8)
    @user.password = generated_password
    @user.password_confirmation = generated_password
    
    Pony.mail({
      :to => @user.email,
      :subject => 'Chi Phi CoLab Password',
      :body => generated_password,
      :via => :smtp,
      :via_options => {
        :address => 'smtp.gmail.com',
        :port => '587',
        :enable_starttls_auto => true,
        :user_name => ENV['CHI_PHI_COLAB_EMAIL_ADDR'],
        :password => ENV['CHI_PHI_COLAB_EMAIL_PASS'],
        :authentication => :plain,
        :domain => 'localhost.localdomain'
      }
    })

    
    if @user.save
      for group in Group.where(:is_default => true)
        permission = @user.permissions.new
        permission.group = group
        permission.level = 1
        permission.save
      end
      
      redirect_to users_path, :notice => "User created."
    else
      redirect_to users_path, :notice => "User could not be created."
    end
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update_with_password(params[:user])
      redirect_to root_url, :notice => 'Password successfully updated.'
    else
      redirect_to root_url, :notice => 'Password update failed.'
    end
  end

  def destroy
  end

  private

  def require_admin_priv
    unless current_user.has_permission(1, 5)
      flash[:error] = "You must be an administrator to do this."
      redirect_to groups_url, :notice => "You must be an administrator to do this."
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Edit Account</h1>

<%= form_for(@user, :url => {:action => "update"}) do |f| %>
  <div class="field">
    <%= f.label :current_password %>
    <%= f.password_field :current_password %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="action">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>User List<%= link_to "Create User", new_user_path, :class => "btn btn-primary btn-success pull-right" %> </h1>

<table class="table">
<tr>
  <th>Email</th>
  <th>Groups</th>
</tr>
<% for user in @users %>
  <tr>
    <td><%= link_to user.email, user %></td>
    <td><%= user.groups.count %></td>
  </tr>
<% end %>
</table>

app/views/users/new.html.erb
<h1>Create User</h1>
<%= form_for @user do |f| %>
  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true %></div>
  <div><%= f.submit "Create User" %></div>
<% end %>

app/views/users/show.html.erb
<h1><small>Users:</small> <%= @user.email %></h1>

<table class="table">
<tr>
  <th>Group</th>
  <th>Level</th>
  <th></th>
</tr>
<% for permission in @permissions %>
<tr>
  <td><%= permission.group.name %><td>
  <td><%= permission.level %></td>
  <td><%= link_to 'Edit', edit_group_permission_url(permission.group, permission) %>
</tr>
<% end %>
</table>