config/routes.rb
Colab::Application.routes.draw do
  resources :discussions do
    resources :posts
  end

  resources :groups do
    resources :permissions
    resources :events
  end

  devise_for :users, :controllers => {:registrations => "registrations"}
  scope "/admin" do
    resources :users
  end

  root :to => 'groups#index'

end

app/models/permission.rb
class Permission < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  attr_accessible :level, :user_id, :group_id
end

app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController
  # GET /permissions
  # GET /permissions.json
  def index
    @group = Group.find(params[:group_id])
    @permissions = @group.permissions

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @permissions }
    end
  end

  # GET /permissions/1
  # GET /permissions/1.json
  def show
    @permission = Permission.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @permission }
    end
  end

  # GET /permissions/new
  # GET /permissions/new.json
  def new
    @group = Group.find(params[:group_id])
    @permission = @group.permissions.new
    
    @user = User.where(:email => params[:user_email]).first

    respond_to do |format|
      if Permission.where(:group_id => @group.id, :user_id => @user.id).exists?
        format.html { redirect_to(@group, :notice => 'User already exists.') }
        format.json { render json: group_url(@group) }
      elsif @user
        format.html # new.html.erb
        format.json { render json: @permission }
      else
        format.html { redirect_to(@group, :notice => 'User not found.') }
        format.json { render json: group_url(@group) }
      end
    end
  end

  # GET /permissions/1/edit
  def edit
    @permission = Permission.find(params[:id])
  end

  # POST /permissions
  # POST /permissions.json
  def create
    @group = Group.find(params[:group_id])
    @permission = @group.permissions.new(params[:permission])

    respond_to do |format|
      if @permission.save
        format.html { redirect_to group_permission_url(@permission.group, @permission), notice: 'Permission was successfully created.' }
        format.json { render json: @permission, status: :created, location: @permission }
      else
        format.html { render action: "new" }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /permissions/1
  # PUT /permissions/1.json
  def update
    @permission = Permission.find(params[:id])

    respond_to do |format|
      if @permission.update_attributes(params[:permission])
        format.html { redirect_to [@permission.group, @permission], notice: 'Permission was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permissions/1
  # DELETE /permissions/1.json
  def destroy
    @permission = Permission.find(params[:id])
    @permission.destroy

    respond_to do |format|
      format.html { redirect_to group_url(params[:group_id]) }
      format.json { head :no_content }
    end
  end
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/views/permissions/_form.html.erb
<%= form_for([@permission.group, @permission]) do |f| %>
  <% if @permission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@permission.errors.count, "error") %> prohibited this permission from being saved:</h2>

      <ul>
      <% @permission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :level %><br />
    <%= f.number_field :level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/permissions/edit.html.erb
<h1>Editing permission</h1>

<%= render 'form' %>

<%= link_to 'Show', group_permission_url(@permission.group, @permission) %> |
<%= link_to 'Back', group_permissions_path(@permission.group) %>

app/views/permissions/index.html.erb
<h1><small>Group > <%= @group.name %> ></small> Permissions</h1>

<table class="table">
  <tr>
    <th>User</th>
    <th>Level</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% for permission in @permissions %>
  <tr>
    <td><%= permission.user.email %></td>
    <td><%= permission.level %></td>
      <td><%= link_to 'Show', group_permission_url(@group, permission) %></td>
      <td><%= link_to 'Edit', edit_group_permission_path(@group, permission) %></td>
      <td><%= link_to 'Destroy', [@group, permission], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/permissions/new.html.erb
<h1>New permission</h1>

<%= form_for([@group, @group.permissions.build]) do |f| %>
  <%= f.hidden_field(:user_id, :value => @user.id) %>
  <div class="field">
    <%= f.label :level %><br />
    <%= f.text_field :level %><br />
  </div>
<% end %>

<%= link_to 'Back', group_permissions_path %>

app/views/permissions/show.html.erb
<p>
  <b>User:</b>
  <%= @permission.user.email %>
</p>

<p>
  <b>Group:</b>
  <%= @permission.group.name %>
</p>

<p>
  <b>Level:</b>
  <%= @permission.level %>
</p>


<%= link_to 'Edit', edit_group_permission_path(@permission.group, @permission) %> |
<%= link_to 'Back', group_permissions_path(@permission.group, @permission) %>